//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by key_macro.rc
//
#define IDD_KEY_MACRO_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_ADD_KEY              129
#define IDR_MAINFRAME1                  129
#define IDR_MAINFRAME2                  129
#define IDD_DIALOG_ADD_DELAY            130
#define IDD_DIALOG_ADD_MOUSE            131
#define IDD_DIALOG_MACRO_EDIT           132
#define IDD_DIALOG_MACRO_REC            133
#define IDD_DIALOG_ADD_STRING           134
#define IDD_DIALOG_ADD_MACRO            135
#define IDD_DIALOG_CONFIG               136
#define IDD_DIALOG_ADD_CS               137
#define IDD_DIALOG_ADD_LOOP             138
#define IDD_DIALOG_USER_LOOP            139
#define IDD_DIALOG_MACRO_START          140
#define IDD_DIALOG_KEY_MOUSE_STATUS     141
#define IDB_BITMAP_LAMP_DISABLED        142
#define IDD_DIALOG_MACRO_DEBUG          142
#define IDB_BITMAP_LAMP_OFF             143
#define IDB_BITMAP_LAMP_ON              144
#define IDC_LIST_MACROS                 1000
#define IDC_LIST_MACROS2                1001
#define IDC_LIST_ITEMS                  1004
#define IDC_BUTTON_ADD_KEY              1005
#define IDC_BUTTON_ADD_MOUSE            1006
#define IDC_EDIT_DELAY                  1006
#define IDC_BUTTON_ADD_DELAY            1007
#define IDC_BUTTON_DELETE               1008
#define IDC_RADIO_KEY_3                 1008
#define IDC_RADIO_DELAY                 1008
#define IDC_BUTTON_ADD_MACRO            1009
#define IDC_RADIO_KEY_1                 1009
#define IDC_RADIO_TIME                  1009
#define IDC_BUTTON_DELETE_MACRO         1010
#define IDC_RADIO_KEY_2                 1010
#define IDC_BUTTON_EDIT                 1010
#define IDC_RADIO_KEY                   1010
#define IDC_BUTTON_EDIT_MACRO           1011
#define IDC_CHECK_MOVE                  1011
#define IDC_CHECK_REC_KEYBOARD          1011
#define IDC_CHECK_RANDOM_CHAR           1011
#define IDC_RADIO_COLOR                 1011
#define IDC_CHECK_WHEEL                 1012
#define IDC_BUTTON_MACRO_FILE           1012
#define IDC_CHECK_REC_MOUSE_BUTTON      1012
#define IDC_CHECK_SEQUENCE_NUMBER       1012
#define IDC_EDIT_CURPOS_X               1013
#define IDC_EDIT_MACRO_FILE             1013
#define IDC_CHECK_REC_MOUSE_MOVE        1013
#define IDC_EDIT_MACRO_REPEAT_COUNT     1013
#define IDC_EDIT_STRING                 1013
#define IDC_EDIT_MESSAGE                1013
#define IDC_RADIO_MACRO_RUN             1014
#define IDC_EDIT_CURPOS_Y               1014
#define IDC_CHECK_REC_TIME_DELAY        1014
#define IDC_EDIT_EVENT_DELAY            1014
#define IDC_BUTTON_DISPLAY_MOUSE        1014
#define IDC_CHECK_COMMENT               1014
#define IDC_RADIO_MACRO_EDIT            1015
#define IDC_RADIO_BUTTON_UP             1015
#define IDC_BUTTON_UP                   1015
#define IDC_CHECK_REC_MOUSE_WHEEL       1015
#define IDC_COMBO_KEYBOARD              1016
#define IDC_BUTTON_REC_MACRO            1016
#define IDC_BUTTON_DOWN                 1016
#define IDC_COMBO_HOUR                  1016
#define IDC_CHECK_REC_KEY2              1016
#define IDC_CHECK_REC_MERGE_UP_DOWN     1016
#define IDC_COMBO_MACRO_STOP            1017
#define IDC_BUTTON_DELETE_MACRO2        1017
#define IDC_EDIT_EVENT_DELAY2           1017
#define IDC_EDIT_EVENT_MIN_DELAY        1017
#define IDC_CHECK_BUTTON_MERGE2         1017
#define IDC_CHECK_MOUSE_POS_SCRINDEP    1017
#define IDC_BUTTON_CONFIG               1017
#define IDC_COMBO_MACRO_START           1018
#define IDC_BUTTON_COPY_MACRO           1018
#define IDC_CHECK_MOUSE_POS_ABSOLUTE    1018
#define IDC_EDIT_MACRO_LOG              1018
#define IDC_EDIT_MACRO_NAME             1019
#define IDC_COMBO_MIN                   1019
#define IDC_COMBO_MACRO_RUN_EDIT_KEY    1019
#define IDC_CHECK_REC_MOUSE_BUTTON_POS  1019
#define IDC_BUTTON_KEY_MOUSE_STATUS     1019
#define IDC_COMBO_SEC                   1020
#define IDC_BUTTON_UP2                  1020
#define IDC_BUTTON_ADD_STRING           1020
#define IDC_COMBO_RECORD_START_STOP_KEY 1020
#define IDC_EDIT_MACRO_REPEAT_COUNT2    1020
#define IDC_BUTTON_DISPLAY_MOUSE2       1021
#define IDC_BUTTON_ERASE_MOUSE          1021
#define IDC_BUTTON_DOWN2                1021
#define IDC_COMBO_MOUSE_CAPTURE_KEY     1021
#define IDC_COMBO_HOUR2                 1021
#define IDC_COMBO_STOP_HOUR             1021
#define IDC_BUTTON_TEST_RUN             1022
#define IDC_BUTTON_SAVE                 1022
#define IDC_COMBO_MIN2                  1022
#define IDC_EDIT_SEQUENCE_START         1022
#define IDC_COMBO_STOP_MIN              1022
#define IDC_BUTTON_ERASE_MOUSE2         1023
#define IDC_BUTTON_STOP                 1023
#define IDC_COMBO_SEC2                  1023
#define IDC_COMBO_STOP_SEC              1023
#define IDC_COMBO_COLOR_START_KEY       1023
#define IDC_BUTTON_KEY_MOUSE_STATUS2    1023
#define IDC_BUTTON_MACRO_DEBUG          1023
#define IDC_BUTTON_ADD_CS               1024
#define IDC_COMBO_COLOR_STOP_KEY        1024
#define IDC_BUTTON_ADD_CS2              1025
#define IDC_BUTTON_ADD_LOOP             1025
#define IDC_COMBO_HANGUL_KEYBOARD       1025
#define IDC_RADIO_BUTTON_CLICK          1029
#define IDC_RADIO_BUTTON_DOWN           1030
#define IDC_EDIT_ABSPOS_X               1031
#define IDC_EDIT_TIME                   1031
#define IDC_EDIT_ABSPOS_Y               1032
#define IDC_EDIT_MOVE                   1032
#define IDC_EDIT_WHEEL                  1033
#define IDC_STATIC_HOMEPAGE             1036
#define IDC_STATIC_HOMEPAGE2            1037
#define IDC_CHECK_REC_STAT              1037
#define IDC_STATIC_VERSION              1037
#define IDC_CHECK_ALWAYS_ON_TOP         1038
#define IDC_STATIC_REC_COUNT            1039
#define IDC_CHECK_TRAY_AT_STARTUP       1039
#define IDC_COMBO_BUTTON_SELECT         1040
#define IDC_STATIC_REC_COUNT2           1040
#define IDC_CHECK_RUN_SEL_MACRO         1041
#define IDC_COMBO_MACRO                 1042
#define IDC_CHECK_SEL_MACRO_RUN2        1042
#define IDC_CHECK_MACRO_KEY_REENTRANCE  1042
#define IDC_CHECK_AUTO_START            1043
#define IDC_CHECK_USE_MM_TIMER          1043
#define IDC_CHECK_MACRO_LOG             1043
#define IDC_CHECK_START_STOP_KEY        1044
#define IDC_CHECK_MACRO_NOTIFY          1044
#define IDC_CHECK_SELECTED_ITEM         1045
#define IDC_STATIC_MESSAGE              1045
#define IDC_CHECK_MACRO_NOTIFY2         1045
#define IDC_CHECK_START_STOP_MARK       1045
#define IDC_STATIC_MESSAGE1             1046
#define IDC_CHECK_RELEASE_ALL_KEYS      1046
#define IDC_RADIO_CS_ENTER              1047
#define IDC_STATIC_MESSAGE2             1047
#define IDC_RADIO_CS_LEAVE              1048
#define IDC_COMBO_RANDOM                1049
#define IDC_RADIO_LOOP_ENTER            1050
#define IDC_RADIO_LOOP_LEAVE            1051
#define IDC_EDIT_LOOP_START             1052
#define IDC_EDIT_LOOP_START2            1053
#define IDC_EDIT_LOOP_START3            1054
#define IDC_CHECK_USER_SET              1055
#define IDC_STATIC_TIMEOUT_MESSAGE      1056
#define IDC_RADIO_LOOP_PRINT            1056
#define IDC_RADIO_SEQUENCE              1057
#define IDC_RADIO_LOOP_MOUSE_X          1057
#define IDC_RADIO_PARALLEL              1058
#define IDC_RADIO_LOOP_MOUSE_Y          1058
#define IDC_CHECK_KEY                   1059
#define IDC_RADIO_PARALLEL2             1059
#define IDC_RADIO_STOP                  1059
#define IDC_CHECK_KEY2                  1060
#define IDC_CHECK_KEY3                  1061
#define IDC_CHECK_COLOR                 1061
#define IDC_EDIT1                       1062
#define IDC_EDIT_START_R                1062
#define IDC_EDIT_INPUT_KEY              1062
#define IDC_EDIT2                       1063
#define IDC_EDIT_START_G                1063
#define IDC_EDIT_MOUSE_POS              1063
#define IDC_EDIT3                       1064
#define IDC_EDIT_START_B                1064
#define IDC_EDIT_IME_HAN_ENG            1064
#define IDC_EDIT5                       1066
#define IDC_EDIT_STOP_R                 1066
#define IDC_EDIT6                       1067
#define IDC_EDIT_STOP_G                 1067
#define IDC_EDIT7                       1068
#define IDC_EDIT_STOP_B                 1068
#define IDC_CHECK_START_SHIFT2          1071
#define IDC_EDIT11                      1072
#define IDC_CHECK1                      1072
#define IDC_CHECK_HIDE_MACRO_TEST       1072
#define IDC_EDIT1_RGB_TOLERANCE         1072
#define IDC_EDIT_RGB_TOLERANCE          1072
#define IDC_CHECK_HANGUL                1072
#define IDC_CHECK_IME_HAN_ENG           1072
#define IDC_EDIT12                      1073
#define IDC_EDIT_START_X                1073
#define IDC_EDIT13                      1074
#define IDC_EDIT1_START_Y               1074
#define IDC_EDIT_START_Y                1074
#define IDC_EDIT14                      1075
#define IDC_EDIT_STOP_X                 1075
#define IDC_EDIT15                      1076
#define IDC_EDIT_STOP_Y                 1076
#define IDC_CHECK_CTRL_START            1077
#define IDC_CHECK_ALT_START             1078
#define IDC_CHECK_SHIFT_START           1079
#define IDC_CHECK_CTRL_STOP             1080
#define IDC_CHECK_ALT_STOP              1081
#define IDC_CHECK_SHIFT_STOP            1082
#define IDC_BUTTON_COLOR_PICK_START     1083
#define IDC_BUTTON_START_COLOR_PICK     1083
#define IDC_BUTTON_COLOR_PICK_START2    1084
#define IDC_BUTTON_COLOR_PICK_STOP      1084
#define IDC_BUTTON_STOP_COLOR_PICK      1084
#define IDC_CHECK_START_PUSH            1085
#define IDC_CHECK_START_CTRL            1086
#define IDC_CHECK_START_ALT             1087
#define IDC_CHECK_START_SHIFT           1088
#define IDC_CHECK_STOP_CTRL             1089
#define IDC_CHECK_STOP_ALT              1090
#define IDC_CHECK_STOP_SHIFT            1091
#define IDC_COMBO_START_KEY             1092
#define IDC_COMBO_STOP_KEY              1093
#define IDC_CHECK_STOP_PUSH             1094
#define IDC_COMBO_START_HOUR            1095
#define IDC_COMBO_START_MIN             1096
#define IDC_COMBO_START_SEC             1097
#define IDC_STATIC_START_COLOR          1098
#define IDC_STATIC_STOP_COLOR           1099
#define IDC_BUTTON_MACRO_START_STOP     1099
#define IDC_EDIT_LOOP_STOP              1100
#define IDC_EDIT_LOOP_STEP              1101
#define ID_QUIT                         1102
#define IDC_CHECK_START_KEY             1103
#define IDC_CHECK_STOP_KEY              1104
#define IDC_BUTTON_APPLY                1104
#define IDC_CHECK_START_COLOR           1105
#define IDC_CHECK_START_COLOR2          1106
#define IDC_CHECK_STOP_COLOR            1106
#define IDC_CHECK2                      1107
#define IDC_CHECK_ONCE                  1107
#define IDC_STATIC_LAMP_CTRL            1108
#define IDC_STATIC_LAMP_ALT             1109
#define IDC_STATIC_LAMP_SHIFT           1110
#define IDC_COMBO_KEY                   1110
#define IDC_STATIC_LAMP_LEFT            1111
#define IDC_CHECK_PUSH                  1111
#define IDC_STATIC_LAMP_MIDDLE          1112
#define IDC_CHECK_CTRL                  1112
#define IDC_STATIC_LAMP_RIGHT           1113
#define IDC_CHECK_ALT                   1113
#define IDC_STATIC_LAMP_X1              1114
#define IDC_CHECK_SHIFT                 1114
#define IDC_STATIC_LAMP_X2              1115
#define IDC_EDIT_R                      1115
#define IDC_EDIT_G                      1116
#define IDC_EDIT_B                      1117
#define IDC_EDIT_X                      1118
#define IDC_EDIT_Y                      1119
#define IDC_EDIT_TOL                    1120
#define IDC_BUTTON_COLOR_PICK           1121
#define IDC_STATIC_COLOR                1122
#define IDC_EDIT_TITLE                  1123
#define IDC_CHECK_MODIFIER              1123
#define IDC_RADIO_MACRO                 1124
#define IDC_RADIO_EVENT                 1125
#define IDC_EDIT4                       1126
#define IDC_EDIT_LOG                    1126
#define IDC_CHECK_START_MODIFIER        1127
#define IDC_CHECK_START_MODIFIER2       1128
#define IDC_CHECK_STOP_MODIFIER         1128

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
